### ISSUE TITLE
Select multiple entries

### ISSUE THREAD

**Issue by luukdewaalmalefijt-ebcont** [FontoXML/fontoxml-cms-browser#8]
A client wants to insert multiple entries at the same time into a section by selecting them in a cms-browser window. 

It would be great to have a configuration option that could configure whether a cms-browser dialog should allow a multiple selection or just a single, as the behaviour is currently.

**Comment by DrRataplan** [comment]
Hello there!

Sorry for the long delay. I think the best course of action to getting this built by us is by filing a [support request](support.fontoxml.com). That way it will be tracked properly. I can not give promises when this will be done though, since we have quite the sizeable backlog already.

In the meantime, I think building such a feature should not be _too_ difficult. I would recommend to fork this package to build a way of selecting multiple items. This package is mainly serving as an example for any custom modals you might want to have on your editor.

I hope this helps you.

Regards,

Martin Middel
